services:
  db:
    image: mysql@sha256:072f96c2f1ebb13f712fd88d0ef98f2ef9a52ad4163ae67b550ed6720b6d642e
    expose:
      - 3306:3306
    restart: unless-stopped
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_pass_file
    secrets:
      - db_root_pass_file

  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    networks:
      - backend
    depends_on:
      - db

  front:
    build:
      dockerfile: dockerfile
      context: ./client/
    restart: unless-stopped
    depends_on:
      - back

  back:
    build:
      dockerfile: dockerfile
      context: ./server/
    restart: unless-stopped
    secrets:
      - jwt_secret
      - db_root_pass_file
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:
