services:
  db:
    container_name: is-proj-db
    ports:
      - 3306:3306
    volumes:
      - is-proj-db-volume:/var/lib/mysql
      - ./datasets/sql:/docker-entrypoint-initdb.d/:ro
  
  phpmyadmin:
    ports:
      - "6002:80"
    environment:
      PMA_HOST: db

  front:
    ports:
      - 5173:5173

  back:
    ports:
      - 3000:3000


secrets:
  db_root_pass_file:
    file: ./secrets/db_root_pass
  jwt_secret:
    file: ./secrets/jwt_secret
volumes:
  is-proj-db-volume:
