<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CVEService"
             targetNamespace="http://example.com/cve"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://example.com/cve"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <message name="getCVECountByLanguageRequest">
    <part name="language" type="xsd:string"/>
  </message>

  <message name="getCVECountByLanguageResponse">
    <part name="count" type="xsd:int"/>
  </message>

  <portType name="CVEServicePortType">
    <operation name="getCVECountByLanguage">
      <input message="tns:getCVECountByLanguageRequest"/>
      <output message="tns:getCVECountByLanguageResponse"/>
    </operation>
  </portType>

  <binding name="CVEServiceBinding" type="tns:CVEServicePortType">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="getCVECountByLanguage">
      <soap:operation soapAction="getCVECountByLanguage"/>
      <input><soap:body use="literal"/></input>
      <output><soap:body use="literal"/></output>
    </operation>
  </binding>

  <service name="CVEService">
    <port name="CVEServicePort" binding="tns:CVEServiceBinding">
      <soap:address location="http://localhost:3000/api/v1/soap"/>
    </port>
  </service>

</definitions>

