module.exports = (sequelize, DataTypes) => {
  return sequelize.define('LangPopularity', {
    Date: { type: DataTypes.DATEONLY, primaryKey: true },
    Abap: DataTypes.FLOAT,
    Ada: DataTypes.FLOAT,
    C_Cpp: DataTypes.FLOAT,
    Csharp: DataTypes.FLOAT,
    Cobol: DataTypes.FLOAT,
    Dart: DataTypes.FLOAT,
    Delphi_Pascal: DataTypes.FLOAT,
    Go: DataTypes.FLOAT,
    Groovy: DataTypes.FLOAT,
    Haskell: DataTypes.FLOAT,
    Java: DataTypes.FLOAT,
    JavaScript: DataTypes.FLOAT,
    Julia: DataTypes.FLOAT,
    Kotlin: DataTypes.FLOAT,
    Lua: DataTypes.FLOAT,
    Matlab: DataTypes.FLOAT,
    Objective_C: DataTypes.FLOAT,
    Perl: DataTypes.FLOAT,
    PHP: DataTypes.FLOAT,
    Powershell: DataTypes.FLOAT,
    Python: DataTypes.FLOAT,
    R: DataTypes.FLOAT,
    Ruby: DataTypes.FLOAT,
    Rust: DataTypes.FLOAT,
    Scala: DataTypes.FLOAT,
    Swift: DataTypes.FLOAT,
    TypeScript: DataTypes.FLOAT,
    VBA: DataTypes.FLOAT,
    Visual_Basic: DataTypes.FLOAT
  }, { timestamps: false, tableName: 'LangPopularity' });
};
